title: Dovydas Ciomenas Portfolio
logo: /assets/img/logo.png
description: Recently graduated from The University of Nottingham, currently looking for junior software engineering positions
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
