title: Dovydas Ciomenas Portfolio
logo: /assets/img/logo.png
description: Recently graduated from The University of Nottingham, currently looking for junior software engineering positions.
show_downloads: false
show_social: true
google_analytics:
theme: jekyll-theme-minimal

# Social
social_github_url: https://github.com/icouldbreathe
social_linkedin_url: https://www.linkedin.com/in/ciomenas/
social_flickr_url: https://www.flickr.com/photos/ayol