title: Dovydas Ciomenas Portfolio
logo: /assets/img/logo.png
description: Software Engineering graduate from The University of Nottingham, currently looking for junior software engineering positions.
show_downloads: false
show_social: true
google_analytics: UA-139209187-1
theme: jekyll-theme-minimal

author: Dovydas Ciomenas

posts_enabled: false

collections:
  projects:
    output: true
  pages:
    output: true
  experimental:
    output: true


exclude: [_experimental/node_modules, _experimental/src, _experimental/package.json, _experimental/package-lock.json]


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "empty"
  - scope:
      path: ""
    values:
      layout: "default"

# Social
social_github_url: https://github.com/icouldbreathe
social_linkedin_url: https://www.linkedin.com/in/ciomenas/
social_flickr_url: https://www.flickr.com/photos/ayol